# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller  
    - name: Build
      run: |
        pyinstaller -F my_script.py -n FtpShare 

    - name: Package
      working-directory: .
      run: |
        #tar -zcvf ftpshare.tar.gz -C ./dist * 
        pwd
        tar -zcvf ftpshare.tar.gz -C dist

    - name: Upload assets
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.tag_name }}
        asset_path: ftpshare.tar.gz
        asset_name: ftpshare.tar.gz
        asset_content_type: application/gzip
